# -*- coding: utf-8 -*-
"""PM project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRJJDEtLH-LiRENr5qFVJKivWlViRSZV

## Neural network training
"""

import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd
import optax
from flax import nnx
import joblib
from sklearn.model_selection import train_test_split

# =====================================================================
# --- 1. DATA PREPARATION & CLEANING ---
# =====================================================================
print("📊 Loading and preparing historical building data...")
df = pd.read_csv('building_dataset_v2.csv')

# Setup target field arrays mapping directly to raw phase records
planned_cost_inputs = ['Est_Cost_site_work', 'Est_Cost_substructure', 'Est_Cost_superstructure', 'Est_Cost_envelope', 'Est_Cost_mep', 'Est_Cost_finishes']
planned_time_inputs = ['Est_Dur_site_work', 'Est_Dur_substructure', 'Est_Dur_superstructure', 'Est_Dur_envelope', 'Est_Dur_mep', 'Est_Dur_finishes']
cost_phases = ['Act_Cost_site_work', 'Act_Cost_substructure', 'Act_Cost_superstructure', 'Act_Cost_envelope', 'Act_Cost_mep', 'Act_Cost_finishes']
time_phases = ['Act_Dur_site_work', 'Act_Dur_substructure', 'Act_Dur_superstructure', 'Act_Dur_envelope', 'Act_Dur_mep', 'Act_Dur_finishes']
output_cols = cost_phases + time_phases

# Cast values to numeric and drop incomplete row targets safely
numeric_cols = ['Total Area (m2)', 'Floors', 'Floor Height (m)', 'Estimated Cost (EUR)', 'Estimated Duration (Days)'] + planned_cost_inputs + planned_time_inputs + output_cols
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df = df.dropna(subset=numeric_cols + ['Building Type'])

# =====================================================================
# --- 1.2 CONDITIONAL WEIGHT EXTRACTION & FEATURE ENGINEERING ---
# =====================================================================
type_cost_weights = {}
type_time_weights = {}

# Compute historical baseline allocation distributions per specific project category
for b_type in df['Building Type'].unique():
    sub_df = df[df['Building Type'] == b_type]

    c_w = sub_df[planned_cost_inputs].div(sub_df[planned_cost_inputs].sum(axis=1), axis=0).mean().values.tolist()
    t_w = sub_df[planned_time_inputs].div(sub_df[planned_time_inputs].sum(axis=1), axis=0).mean().values.tolist()

    type_cost_weights[b_type] = c_w
    type_time_weights[b_type] = t_w

# Logic Injection Engineering: global ratio thresholds and scaled targets
total_actual = df[cost_phases].sum(axis=1)
df['Historical_Overrun_Ratio'] = total_actual / df['Estimated Cost (EUR)']
global_overrun_avg = df['Historical_Overrun_Ratio'].mean()

avg_cost_weights_global = df[cost_phases].div(df[cost_phases].sum(axis=1), axis=0).mean()
for i in range(6):
    df[f'Scaled_Phase_Cost_{i}'] = df['Estimated Cost (EUR)'] * avg_cost_weights_global.iloc[i] * global_overrun_avg

engineered_inputs = [f'Scaled_Phase_Cost_{i}' for i in range(6)]
continuous_input_cols = ['Total Area (m2)', 'Floors', 'Floor Height (m)', 'Estimated Cost (EUR)', 'Estimated Duration (Days)'] + planned_cost_inputs + planned_time_inputs + engineered_inputs

# Build structured matrix inputs with categorical one-hot vectors
proj_dummies = pd.get_dummies(df['Building Type'], prefix='Type')
X_raw = pd.concat([proj_dummies, df[continuous_input_cols]], axis=1).values.astype(np.float32)
Y_raw = df[output_cols].values.astype(np.float32)
param_cols = pd.concat([proj_dummies, df[continuous_input_cols]], axis=1).columns.tolist()

num_params, num_output = len(param_cols), len(output_cols)

# Define global normalization bounding vectors
p_min, p_max = X_raw.min(axis=0), X_raw.max(axis=0)
o_min, o_max = Y_raw.min(axis=0), Y_raw.max(axis=0)
p_range = np.where((p_max - p_min) == 0, 1.0, p_max - p_min)
o_range = np.where((o_max - o_min) == 0, 1.0, o_max - o_min)

# =====================================================================
# --- 1.3 STRATIFIED SHUFFLE SPLIT ---
# =====================================================================
X_train, X_valid, Y_train, Y_valid = train_test_split(
    X_raw,
    Y_raw,
    test_size=0.2,
    shuffle=True,
    random_state=42,
    stratify=df['Building Type']
)

# Convert arrays to normalized JAX matrix structures
X_train_norm, X_valid_norm = jnp.array((X_train - p_min) / p_range), jnp.array((X_valid - p_min) / p_range)
Y_train_norm, Y_valid_norm = jnp.array((Y_train - o_min) / o_range), jnp.array((Y_valid - o_min) / o_range)

# =====================================================================
# --- 2. NEURAL NETWORK ARCHITECTURE DEFINITION ---
# =====================================================================
class ConstructionNN(nnx.Module):
    def __init__(self, rngs: nnx.Rngs):
        self.linear1 = nnx.Linear(num_params, 128, rngs=rngs)
        self.linear2 = nnx.Linear(128, 64, rngs=rngs)
        self.linear3 = nnx.Linear(64, num_output, rngs=rngs)

    def __call__(self, x):
        x = nnx.silu(self.linear1(x))
        x = nnx.silu(self.linear2(x))
        return jax.nn.softplus(self.linear3(x))

model = ConstructionNN(rngs=nnx.Rngs(42))
optimizer = nnx.Optimizer(model, wrt=nnx.Param, tx=optax.adam(5e-4))

# =====================================================================
# --- 3. TRAINING BLOCK WITH PROGRESS MONITORING ---
# =====================================================================
print("\n🚀 Initializing JIT training engine loop...")

@nnx.jit
def train_step(mod, opt, X, Y):
    def loss_fn(m):
        preds = m(X)
        diff = preds - Y
        penalty = jnp.where(diff < 0, 4.0, 1.0)
        return jnp.mean(penalty * (diff**2))

    grads = nnx.grad(loss_fn)(mod)
    opt.update(mod, grads)
    return loss_fn(mod)

@nnx.jit
def eval_loss(mod, X, Y):
    value_preds = mod(X)
    diff = value_preds - Y
    penalty = jnp.where(diff < 0, 4.0, 1.0)
    return jnp.mean(penalty * (diff**2))

# --- NEW: INITIALIZE PROGRESS LOGGING TRACKERS ---
log_epochs = []
log_train_loss = []
log_val_loss = []

# Run structural epoch optimization steps
for epoch in range(2501):
    train_loss = train_step(model, optimizer, X_train_norm, Y_train_norm)

    # Record history every 250 steps to match your verification print cadence
    if epoch % 250 == 0:
        val_loss = eval_loss(model, X_valid_norm, Y_valid_norm)
        print(f"Epoch {epoch:4d} | Train Loss: {float(train_loss):.6f} | Val Loss: {float(val_loss):.6f}")

        # Append history values
        log_epochs.append(epoch)
        log_train_loss.append(float(train_loss))
        log_val_loss.append(float(val_loss))

print("🏁 Training loop processing sequence completed successfully.")

# =====================================================================
# --- 4. EXPORT ARTIFACT PACKAGES ---
# =====================================================================
joblib.dump({
    'model_state': nnx.state(model, nnx.Param),
    'param_cols': param_cols,
    'params_min': p_min, 'params_range': p_range,
    'output_min': o_min, 'output_range': o_range,
    'type_cost_weights': type_cost_weights,
    'type_time_weights': type_time_weights,
    'avg_cost_weights_global': avg_cost_weights_global.values.tolist(),
    'global_overrun_avg': float(global_overrun_avg),
    'encoded_project_cols': [c for c in param_cols if c.startswith('Type_')]
}, 'project_model.pkl')

print("💾 Optimized model states saved into 'project_model.pkl'.")

# Generate post-training validation predictions
validation_predictions_norm = np.array(model(X_valid_norm))
validation_predictions_raw = (validation_predictions_norm * o_range) + o_min

# --- UPDATED: EXPORT INCLUDING THE MISSING TIMELINE ARRAYS ---
np.savez(
    'validation_results.npz',
    X_valid=X_valid,
    Y_valid=Y_valid,
    Y_pred=validation_predictions_raw,
    log_epochs=np.array(log_epochs),            # <--- Added
    log_train_loss=np.array(log_train_loss),    # <--- Added
    log_val_loss=np.array(log_val_loss)         # <--- Added
)

print("💾 Complete evaluation history saved into 'validation_results.npz'.")

import numpy as np
data = np.load('validation_results.npz')
print("Keys in file:", data.files)
print("Number of epochs saved:", len(data['log_epochs']))

import numpy as np
import matplotlib.pyplot as plt

# Load the data
try:
    data = np.load('validation_results.npz', allow_pickle=True)
    epochs = data['log_epochs']
    # --- FIX: Synchronized keys with the training script export ---
    loss_train = data['log_train_loss']
    loss_valid = data['log_val_loss']
    print("📈 Training history loaded successfully.")
except Exception as e:
    print(f"❌ Error loading history: {e}")
else:
    # --- GRAPH: TRAINING HISTORY ---
    if len(epochs) > 0:
        plt.figure(figsize=(10, 5))
        plt.plot(epochs, loss_train, label='Training Loss', linewidth=2, color='#1f77b4')
        plt.plot(epochs, loss_valid, label='Validation Loss', linestyle='--', color='#ff7f0e', linewidth=2)

        plt.yscale('log') # Log scale helps see small changes at the end
        plt.title('Construction Analytics Model: Training History', fontsize=14, fontweight='bold')
        plt.xlabel('Epochs', fontsize=12)
        plt.ylabel('Asymmetric Loss / MSE (Log Scale)', fontsize=12)
        plt.legend(fontsize=11)
        plt.grid(True, which="both", alpha=0.3)
        plt.tight_layout()
        plt.show()
    else:
        print("No training history data found in the file.")

import numpy as np
import matplotlib.pyplot as plt

# Load the data
try:
    data = np.load('validation_results.npz', allow_pickle=True)
    # --- FIX 1: Map to the exact keys exported by the training script ---
    Y_true = data['X_valid'] if 'X_valid' not in data else data['Y_valid'] # Use ground truth targets
    Y_pred = data['Y_pred']

    # --- FIX 2: Generate the exact 12-target string names matching the training output order ---
    cost_phases = ['Act_Cost_site_work', 'Act_Cost_substructure', 'Act_Cost_superstructure', 'Act_Cost_envelope', 'Act_Cost_mep', 'Act_Cost_finishes']
    time_phases = ['Act_Dur_site_work', 'Act_Dur_substructure', 'Act_Dur_superstructure', 'Act_Dur_envelope', 'Act_Dur_mep', 'Act_Dur_finishes']
    labels = cost_phases + time_phases

    print(f"📈 Prediction data loaded: {Y_true.shape[0]} validation samples.")
except Exception as e:
    print(f"❌ Error loading data: {e}")
else:
    # --- GRAPH: 6-PHASE PARITY PLOTS ---
    # Adjusted grid dynamically to 2 rows and 6 columns (for 12 targets total)
    fig, axs = plt.subplots(2, 6, figsize=(24, 9))
    axs = axs.flatten()

    for i in range(12):
        # Scatter plot of actual vs predicted
        axs[i].scatter(Y_true[:, i], Y_pred[:, i], s=12, alpha=0.4, color='#1f77b4')

        # Identity line (The "Perfect Prediction" line)
        low = float(min(Y_true[:, i].min(), Y_pred[:, i].min()))
        high = float(max(Y_true[:, i].max(), Y_pred[:, i].max()))
        axs[i].plot([low, high], [low, high], '--', color='red', linewidth=1.5, label='Perfect Fit')

        # Labels and Grid
        # Shorten or clean labels for presentation
        clean_label = labels[i].replace('Act_Cost_', 'Cost: ').replace('Act_Dur_', 'Days: ').replace('_', ' ').title()

        axs[i].set_title(clean_label, fontsize=11, fontweight='bold')
        axs[i].set_xlabel('Actual Value', fontsize=9)
        axs[i].set_ylabel('Predicted Value', fontsize=9)
        axs[i].grid(True, alpha=0.2)

    plt.suptitle('Prediction Performance Parity: Actual vs. Predicted (Per Phase Grid)', fontsize=18, fontweight='bold', y=0.98)
    plt.tight_layout()
    plt.show()

"""# Preview app"""

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import joblib
from flax import nnx
import jax.numpy as jnp
import jax
import sys
import traceback

# =====================================================================
# --- 1. LOAD ASSETS & HISTORICAL BOUNDS ---
# =====================================================================
try:
    assets = joblib.load('project_model.pkl')

    class ConstructionNN(nnx.Module):
        def __init__(self, input_dim, output_dim, rngs):
            self.linear1 = nnx.Linear(input_dim, 128, rngs=rngs)
            self.linear2 = nnx.Linear(128, 64, rngs=rngs)
            self.linear3 = nnx.Linear(64, output_dim, rngs=rngs)
        def __call__(self, x):
            x = nnx.silu(self.linear1(x))
            x = nnx.silu(self.linear2(x))
            return jax.nn.softplus(self.linear3(x))

    input_dim = len(assets['param_cols'])
    model = ConstructionNN(input_dim, 12, nnx.Rngs(42))
    nnx.update(model, assets['model_state'])
    print(f"✅ Model Assets Loaded Successfully. Features: {input_dim}")
except Exception as e:
    print(f"❌ Error loading 'project_model.pkl': {e}")
    assets = None

try:
    df_raw = pd.read_csv('building_dataset_v2.csv')
    df_raw['cost_per_m2'] = df_raw['Estimated Cost (EUR)'] / df_raw['Total Area (m2)']
    df_raw['days_per_m2'] = df_raw['Estimated Duration (Days)'] / df_raw['Total Area (m2)']

    cost_floor_rates = df_raw.groupby('Building Type')['cost_per_m2'].quantile(0.15).to_dict()
    time_floor_rates = df_raw.groupby('Building Type')['days_per_m2'].quantile(0.15).to_dict()
    print("✅ Logical validation rules calibrated from dataset constraints.")
except Exception as e:
    print(f"⚠️ Dataset fallback applied. Using general heuristics: {e}")
    cost_floor_rates = {'Office building': 1200.0, 'Industrial warehouse': 600.0, 'Residential building': 1400.0, 'Residential house': 1100.0}
    time_floor_rates = {'Office building': 0.15, 'Industrial warehouse': 0.08, 'Residential building': 0.18, 'Residential house': 0.12}

# =====================================================================
# --- 2. UI DESIGN ---
# =====================================================================
style = {'description_width': 'initial'}
building_type = widgets.Dropdown(
    options=['Industrial warehouse', 'Office building', 'Residential building', 'Residential house'],
    value='Office building',
    description="Building Type:",
    style=style
)
area_m2 = widgets.FloatText(value=1000.0, description="Total Area (m²):", style=style)
num_floors = widgets.IntText(value=3, description="Number of Floors:", style=style)
floor_height = widgets.FloatText(value=3.5, description="Floor Height (m):", style=style)
total_cost = widgets.FloatText(value=1500000.0, description="Estimated Cost (EUR):", style=style)
total_time = widgets.IntText(value=200, description="Estimated Duration (Days):", style=style)

phases_list = ["Site Work", "Substructure", "Superstructure", "Envelope", "MEP", "Finishes"]
phase_checks = {p: widgets.Checkbox(description=p) for p in phases_list}
phase_data = {p: widgets.HBox([
    widgets.FloatText(value=0.0, placeholder="Actual EUR", description="Act Cost:", layout={'width': '160px'}, style=style),
    widgets.IntText(value=0, placeholder="Actual Days", description="Act Days:", layout={'width': '160px'}, style=style)
], layout={'display': 'none'}) for p in phases_list}

_is_updating_sequence = False

def toggle_inputs(change):
    global _is_updating_sequence
    if _is_updating_sequence:
        return

    name = change['owner'].description
    new_val = change['new']

    if new_val:
        current_idx = phases_list.index(name)
        for idx in range(current_idx):
            prev_phase = phases_list[idx]
            if not phase_checks[prev_phase].value:
                _is_updating_sequence = True
                change['owner'].value = False
                _is_updating_sequence = False

                with validation_status_box:
                    clear_output(wait=True)
                    display(HTML(f"""
                    <div style='border:2px solid #ff9800; padding:12px; border-radius:8px; font-family:sans-serif; background:#fff3e0; color:#e65100; margin-bottom:15px;'>
                        <h4 style='margin-top:0; font-size:15px; margin-bottom:5px;'>⚠️ Non-Sequential Phase Selection!</h4>
                        <p style='margin:0; font-size:13px;'>You cannot add actual metrics for <b>{name}</b> before completing the preceding stage: <b>{prev_phase}</b>.</p>
                    </div>
                    """))
                return

    phase_data[name].layout.display = 'flex' if change['new'] else 'none'
    validate_inputs_live()

for cb in phase_checks.values():
    cb.observe(toggle_inputs, names='value')

# =====================================================================
# --- 3. ANALYSIS ENGINE ---
# =====================================================================
btn = widgets.Button(description="📈 RUN PREDICTIVE ANALYSIS", button_style='success', layout={'width': '100%', 'height': '50px'})
out = widgets.Output()
validation_status_box = widgets.Output()

def validate_inputs_live(change=None):
    selected_type = building_type.value
    current_area = area_m2.value

    min_logical_cost = current_area * cost_floor_rates.get(selected_type, 1000.0)
    min_logical_time = int(round(current_area * time_floor_rates.get(selected_type, 0.1)))
    if min_logical_time < 30: min_logical_time = 30

    with validation_status_box:
        if total_cost.value < min_logical_cost or total_time.value < min_logical_time:
            clear_output(wait=True)
            btn.disabled = True
            btn.button_style = 'danger'
            btn.description = "🔒 LOCKED: FIX ILLOGICAL INPUT VALUES BELOW"

            display(HTML(f"""
            <div style='border:2px solid #d32f2f; padding:12px; border-radius:8px; font-family:sans-serif; background:#ffebee; color:#c62828; margin-bottom:15px;'>
                <h4 style='margin-top:0; font-size:15px; margin-bottom:5px;'>⚠️ Input Threshold Breach!</h4>
                <p style='margin: 0 0 5px 0; font-size:13px;'>Values are physically unfeasible for a <b>{selected_type}</b> measuring <b>{current_area:,.1f} m²</b>:</p>
                <ul style='margin:0; padding-left:20px; font-size:13px;'>
                    <li>Cost Entered: €{total_cost.value:,.0f} <span style='font-weight:bold;'>(Minimum Limit: €{min_logical_cost:,.0f})</span></li>
                    <li>Duration Entered: {total_time.value} Days <span style='font-weight:bold;'>(Minimum Limit: {min_logical_time} Days)</span></li>
                </ul>
            </div>
            """))
        else:
            btn.disabled = False
            btn.button_style = 'success'
            btn.description = "📈 RUN PREDICTIVE ANALYSIS"
            clear_output(wait=True)

building_type.observe(validate_inputs_live, names='value')
area_m2.observe(validate_inputs_live, names='value')
total_cost.observe(validate_inputs_live, names='value')
total_time.observe(validate_inputs_live, names='value')

def get_forecast():
    if assets is None:
        return np.ones(12)
    proj_vec = [0] * len(assets['encoded_project_cols'])
    try:
        proj_idx = assets['encoded_project_cols'].index(f"Type_{building_type.value}")
        proj_vec[proj_idx] = 1
    except:
        pass

    avg_cost_global = assets.get('avg_cost_weights_global', assets.get('avg_cost_weights', [1/6]*6))
    avg_time_global = assets.get('avg_time_weights', [1/6]*6)

    c_weights = assets.get('type_cost_weights', {}).get(building_type.value, avg_cost_global)
    t_weights = assets.get('type_time_weights', {}).get(building_type.value, avg_time_global)

    split_costs = [total_cost.value * c_weights[i] for i in range(6)]
    split_times = [total_time.value * t_weights[i] for i in range(6)]

    overrun_adj = assets.get('global_overrun_avg', 1.0)
    scaled_costs = [total_cost.value * avg_cost_global[i] * overrun_adj for i in range(6)]

    core_cont = [area_m2.value, num_floors.value, floor_height.value, total_cost.value, total_time.value]

    if len(assets['param_cols']) == 15:
        full_input = proj_vec + core_cont + scaled_costs
    else:
        full_input = proj_vec + core_cont + split_costs + split_times + scaled_costs

    feat = (np.array(full_input) - assets['params_min']) / assets['params_range']
    pred = model(jnp.array([feat]))[0]
    return np.array(pred) * assets['output_range'] + assets['output_min']

def run_analysis(b):
    with out:
        clear_output(wait=True)
        try:
            avg_cost_global = [0.10, 0.15, 0.35, 0.15, 0.15, 0.10]
            avg_time_global = [0.10, 0.15, 0.30, 0.15, 0.15, 0.15]
            if assets:
                avg_cost_global = assets.get('avg_cost_weights_global', assets.get('avg_cost_weights', avg_cost_global))
                avg_time_global = assets.get('avg_time_weights', avg_time_global)

            c_weights = assets.get('type_cost_weights', {}).get(building_type.value, avg_cost_global) if assets else avg_cost_global
            t_weights = assets.get('type_time_weights', {}).get(building_type.value, avg_time_global) if assets else avg_time_global

            if assets:
                nn_out = get_forecast()
                pred_costs = np.maximum(0, nn_out[:6])
                pred_days = np.maximum(1, nn_out[6:])
            else:
                pred_costs = [total_cost.value * c_weights[i] * 1.08 for i in range(6)]
                pred_days = [int(round(total_time.value * t_weights[i] * 1.12)) for i in range(6)]

            # --- 1. COMPUTE SYSTEM BASELINE TIMELINES (PV) ---
            days_planned = [0]
            pv_milestones = [0]
            planned_cumulative_days = 0
            pv_acc = 0

            for i in range(6):
                est_c = total_cost.value * c_weights[i]
                est_d = int(round(total_time.value * t_weights[i]))
                pv_acc += est_c
                planned_cumulative_days += est_d
                pv_milestones.append(pv_acc)
                days_planned.append(planned_cumulative_days)

            # --- 2. COMPUTE ACTUAL AND FORECAST REALITY TIMELINES (AC / EV) ---
            reality_days = [0]
            actual_milestone_costs = [0]
            cur_reality_day = 0
            cur_reality_cost = 0
            actual_count = 0

            for i, p in enumerate(phases_list):
                if phase_checks[p].value:
                    val_d = int(phase_data[p].children[1].value or 1)
                    val_c = float(phase_data[p].children[0].value or 0.0)
                    actual_count += 1
                else:
                    val_d = int(round(pred_days[i]))
                    val_c = float(pred_costs[i])
                cur_reality_day += val_d
                cur_reality_cost += val_c
                reality_days.append(cur_reality_day)
                actual_milestone_costs.append(cur_reality_cost)

            total_planned_days = int(days_planned[-1])
            total_actual_days = int(reality_days[-1])
            max_timeline_days = max(total_planned_days, total_actual_days)

            # --- 3. COMPUTE CONTINUOUS PERFORMANCE VECTORS ---
            daily_pv_rate = np.zeros(max_timeline_days + 1)
            daily_ac_rate = np.zeros(max_timeline_days + 1)
            daily_ev_rate = np.zeros(max_timeline_days + 1)

            # Map Baseline planned value curve
            for i in range(6):
                p_start = days_planned[i]
                p_end = days_planned[i+1]
                p_budget = total_cost.value * c_weights[i]
                if p_end > p_start:
                    daily_pv_rate[p_start:p_end] = p_budget / (p_end - p_start)

            # Map Reality curves (AC and EV)
            for i, p in enumerate(phases_list):
                r_start = reality_days[i]
                r_end = reality_days[i+1]
                p_budget = total_cost.value * c_weights[i]

                if phase_checks[p].value:
                    r_cost = float(phase_data[p].children[0].value or 0.0)
                else:
                    r_cost = float(pred_costs[i])

                if r_end > r_start:
                    daily_ac_rate[r_start:r_end] = r_cost / (r_end - r_start)
                    daily_ev_rate[r_start:r_end] = p_budget / (r_end - r_start)

            cum_pv_daily = np.cumsum(daily_pv_rate)
            cum_ac_daily = np.cumsum(daily_ac_rate)
            cum_ev_daily = np.cumsum(daily_ev_rate)

            # --- 4. WEEK-BY-WEEK EVM MONITORING GENERATOR ---
            current_cutoff_days = reality_days[actual_count]
            total_project_weeks = int(np.ceil(max_timeline_days / 7))
            cutoff_week = int(np.ceil(current_cutoff_days / 7)) if current_cutoff_days > 0 else 0

            weekly_ticks = list(range(1, total_project_weeks + 1))
            weekly_pv, weekly_ac, weekly_ev = [], [], []
            weekly_cpi, weekly_spi = [], []

            for w in weekly_ticks:
                day_idx = min(w * 7, max_timeline_days)

                w_pv = cum_pv_daily[day_idx]
                w_ac = cum_ac_daily[day_idx]
                w_ev = cum_ev_daily[day_idx]

                if w_ac > 0:
                    w_cpi = w_ev / w_ac
                else:
                    w_cpi = 1.0

                if w_ev >= cum_pv_daily[-1]:
                    earned_schedule_days = total_planned_days
                else:
                    pv_match_idx = np.where(cum_pv_daily >= w_ev)[0]
                    earned_schedule_days = pv_match_idx[0] if len(pv_match_idx) > 0 else day_idx

                w_spi = earned_schedule_days / day_idx if day_idx > 0 else 1.0

                if not phase_checks[phases_list[0]].value:
                    w_cpi = 1.0 - (0.04 * (day_idx / max_timeline_days))
                    w_spi = 1.0 - (0.07 * (day_idx / max_timeline_days))

                weekly_pv.append(w_pv)
                weekly_ac.append(w_ac)
                weekly_ev.append(w_ev)
                weekly_cpi.append(np.clip(w_cpi, 0.7, 1.3))
                weekly_spi.append(np.clip(w_spi, 0.7, 1.3))

            cutoff_day_idx = min(current_cutoff_days, max_timeline_days)
            if current_cutoff_days > 0:
                cpi = cum_ev_daily[cutoff_day_idx] / cum_ac_daily[cutoff_day_idx] if cum_ac_daily[cutoff_day_idx] > 0 else 1.0
                cutoff_ev = cum_ev_daily[cutoff_day_idx]
                match_array = np.where(cum_pv_daily >= cutoff_ev)[0]
                es_cutoff_days = match_array[0] if len(match_array) > 0 else cutoff_day_idx
                spi = es_cutoff_days / cutoff_day_idx if cutoff_day_idx > 0 else 1.0
            else:
                cpi = weekly_cpi[-1]
                spi = weekly_spi[-1]

            eac = float(total_cost.value) / cpi if cpi > 0 else float(total_cost.value)

            # --- 5. RENDER UI PERFORMANCE TABLES ---
            rows = ""
            for i, p in enumerate(phases_list):
                est_c = total_cost.value * c_weights[i]
                est_d = int(round(total_time.value * t_weights[i]))
                if phase_checks[p].value:
                    val_c = float(phase_data[p].children[0].value or 0.0)
                    val_d = int(phase_data[p].children[1].value or 1)
                    status = "✅ Actual"
                else:
                    val_c = float(pred_costs[i])
                    val_d = int(round(pred_days[i]))
                    status = "🔮 Forecast"
                rows += f"<tr><td>{p} ({status})</td><td>€{est_c:,.0f}</td><td>{est_d}</td><td>€{val_c:,.0f}</td><td>{val_d}</td></tr>"

            # --- 6. VISUALIZATION ENGINE GENERATION ---
            fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 14))
            plt.subplots_adjust(hspace=0.4, bottom=0.15)

            # --- Plot Subpanel 1: Cumulative Cash Curves ---
            days_arr = np.arange(max_timeline_days + 1)
            ax1.plot(np.arange(total_planned_days + 1), cum_pv_daily[:total_planned_days + 1], color='blue', linestyle=':', linewidth=2, label='Planned Value (PV)', alpha=0.9)

            if current_cutoff_days > 0:
                ax1.plot(days_arr[:current_cutoff_days + 1], cum_ac_daily[:current_cutoff_days + 1], 'r-', linewidth=2.5, label='Actual Cost (AC)')
                ax1.plot(days_arr[:current_cutoff_days + 1], cum_ev_daily[:current_cutoff_days + 1], 'g-', linewidth=2.5, label='Earned Value (EV)')
                ax1.plot(days_arr[current_cutoff_days:], cum_ac_daily[current_cutoff_days:], 'r--', alpha=0.7, label='AI Forecast Extension (EAC)')
                ax1.axvline(x=current_cutoff_days, color='#ff9800', linestyle='--', alpha=0.9, label=f'Monitoring Cutoff (Day {current_cutoff_days})')
            else:
                ax1.plot(days_arr, cum_ac_daily, 'r--', label='Predicted Cost Extension (EAC)')

            ax1.scatter(days_planned, pv_milestones, color='blue', edgecolor='black', s=60, zorder=5, label='PV Phase End Milestone')
            ax1.scatter(reality_days, actual_milestone_costs, color='red', edgecolor='black', s=60, zorder=5, label='AC Phase End Milestone')

            ax1.set_title(f"Earned Value Management ({building_type.value})", fontsize=13, fontweight='bold')
            ax1.set_ylabel("Cumulative Value (€)")
            ax1.set_xlabel("Timeline Accumulated (Days)")

            ax1.legend(loc='upper center', bbox_to_anchor=(0.5, -0.13), fancybox=True, shadow=True, ncol=3)
            ax1.grid(True, alpha=0.2)

            # --- Plot Subpanel 2: Continuous Performance Trends ---
            w_arr = np.array(weekly_ticks)

            if cutoff_week > 0:
                # Actual Metrics Portion (Solid Lines)
                ax2.plot(w_arr[:cutoff_week], weekly_cpi[:cutoff_week], color='#1a237e', linestyle='-', marker='o', markersize=5, linewidth=2.5, label='Actual CPI')
                ax2.plot(w_arr[:cutoff_week], weekly_spi[:cutoff_week], color='#ad1457', linestyle='-', marker='s', markersize=5, linewidth=2.5, label='Actual SPI')

                # Predictive Extension Portion (Dashed Lines + Open Markers)
                ax2.plot(w_arr[cutoff_week-1:], weekly_cpi[cutoff_week-1:], color='#1a237e', linestyle='--', marker='o', markersize=5, markerfacecolor='white', linewidth=2, label='AI Predicted CPI')
                ax2.plot(w_arr[cutoff_week-1:], weekly_spi[cutoff_week-1:], color='#ad1457', linestyle='--', marker='s', markersize=5, markerfacecolor='white', linewidth=2, label='AI Predicted SPI')

                ax2.axvline(x=cutoff_week, color='#ff9800', linestyle='--', alpha=0.8, label=f'Cutoff Week {cutoff_week}')
            else:
                # If no phases are checked, the entire timeline defaults to forecasted indicators
                ax2.plot(w_arr, weekly_cpi, color='#1a237e', linestyle='--', marker='o', markersize=5, markerfacecolor='white', linewidth=2, label='AI Predicted CPI')
                ax2.plot(w_arr, weekly_spi, color='#ad1457', linestyle='--', marker='s', markersize=5, markerfacecolor='white', linewidth=2, label='AI Predicted SPI')

            ax2.axhline(y=1.0, color='black', linestyle='-.', alpha=0.6, label='Target Benchmark (1.0)')
            ax2.set_title("CPI and SPI Continuous Lifecycle Performance Trends", fontsize=13, fontweight='bold')
            ax2.set_xlabel("Weeks")
            ax2.set_ylabel("KPI Ratios")
            ax2.set_ylim(0.6, 1.4)
            ax2.set_xticks(weekly_ticks[::max(1, total_project_weeks // 15)])

            ax2.legend(loc='upper center', bbox_to_anchor=(0.5, -0.15), fancybox=True, shadow=True, ncol=3)
            ax2.grid(True, alpha=0.3)

            plt.show()

            # Display Metadata Panel
            display(HTML(f"""<div style='border:1px solid #388e3c; padding:15px; border-radius:10px; font-family:sans-serif; background:#1e1e1e; color:white;'>
                <h3 style='text-align:center; color:#4caf50; margin-top:0;'>Time-Phased Predictive EVM Analysis</h3>
                <p style='text-align:center; font-size:15px;'><b>Tracking Cutoff Status:</b> Day {current_cutoff_days} (Week {cutoff_week}) | <b>CPI:</b> {cpi:.2f} | <b>SPI:</b> {spi:.2f} | <b>Projected EAC:</b> €{eac:,.0f}</p>
                <table style='width:100%; border-collapse:collapse; color:white; text-align:left;'>
                    <tr style='background:#333; border-bottom:2px solid #4caf50;'>
                        <th style='padding:8px;'>Phase Component</th>
                        <th style='padding:8px;'>Est. Budget</th>
                        <th style='padding:8px;'>Est. Days</th>
                        <th style='padding:8px;'>Act/Pred Cost</th>
                        <th style='padding:8px;'>Act/Pred Days</th>
                    </tr>
                    {rows}
                </table></div>"""))
        except Exception as err:
            print("❌ An error occurred inside live execution calculation block:")
            traceback.print_exc(file=sys.stdout)

btn.on_click(run_analysis)
validate_inputs_live()

# =====================================================================
# --- 4. RENDER LAYOUT ---
# =====================================================================
display(widgets.VBox([
    widgets.HTML("<h2 style='color:#2e7d32; text-align:center; font-family:sans-serif; margin-bottom:5px;'>AI Forecast Earned Value Management Tool</h2>"),
    building_type, area_m2, num_floors, floor_height, total_cost, total_time,
    widgets.HTML("<hr><p style='font-weight:bold; color:#1b5e20;'>Update Active Progress (Check to override AI with actual numbers):</p>"),
    widgets.VBox([widgets.HBox([phase_checks[p], phase_data[p]]) for p in phases_list]),
    widgets.HTML("<br>"),
    validation_status_box,
    btn, out
]))

"""# Streamlit Web Application"""

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# import plotly.graph_objects as go
# from flax import nnx
# import jax.numpy as jnp
# import jax
# 
# # --- 1. MODEL RECONSTRUCTION ---
# class ConstructionNN(nnx.Module):
#     def __init__(self, input_dim, output_dim, rngs):
#         self.linear1 = nnx.Linear(input_dim, 128, rngs=rngs)
#         self.linear2 = nnx.Linear(128, 64, rngs=rngs)
#         self.linear3 = nnx.Linear(64, output_dim, rngs=rngs)
# 
#     def __call__(self, x):
#         x = nnx.silu(self.linear1(x))
#         x = nnx.silu(self.linear2(x))
#         return jax.nn.softplus(self.linear3(x))
# 
# @st.cache_resource
# def load_assets():
#     try:
#         assets = joblib.load("project_model.pkl")
#         model = ConstructionNN(len(assets['param_cols']), 12, nnx.Rngs(42))
#         nnx.update(model, assets['model_state'])
#         return model, assets
#     except Exception as e:
#         st.error(f"Error loading assets: {e}")
#         return None, None
# 
# model, assets = load_assets()
# 
# # --- CONFIGURATION ---
# st.set_page_config(page_title="Predictive EVM Dashboard", layout="wide")
# st.title("🏗️ Time-Phased Predictive EVM Dashboard")
# st.markdown("---")
# 
# if assets:
#     # --- PART 1: PROJECT PARAMETERS ---
#     st.sidebar.header("1. Scope & Geometrical Parameters")
#     building_type = st.sidebar.selectbox("Building Type", ['Industrial warehouse', 'Office building', 'Residential building', 'Residential house'])
#     area_m2 = st.sidebar.number_input("Total Area (m²)", min_value=1.0, value=1000.0)
#     num_floors = st.sidebar.number_input("Number of Floors", min_value=1, value=3, step=1)
#     floor_height = st.sidebar.number_input("Floor Height (m)", min_value=1.0, value=3.5)
#     total_cost = st.sidebar.number_input("Estimated Cost (€)", min_value=1000.0, value=1500000.0)
#     total_time = st.sidebar.number_input("Estimated Duration (Days)", min_value=1, value=200, step=1)
# 
#     cost_floor_rates = {'Office building': 1200.0, 'Industrial warehouse': 600.0, 'Residential building': 1400.0, 'Residential house': 1100.0}
#     time_floor_rates = {'Office building': 0.15, 'Industrial warehouse': 0.08, 'Residential building': 0.18, 'Residential house': 0.12}
# 
#     min_logical_cost = area_m2 * cost_floor_rates.get(building_type, 1000.0)
#     min_logical_time = int(round(area_m2 * time_floor_rates.get(building_type, 0.1)))
#     if min_logical_time < 30: min_logical_time = 30
# 
#     if total_cost < min_logical_cost or total_time < min_logical_time:
#         st.error(f"⚠️ **Input Threshold Breach!** Values are physically unfeasible for a **{building_type}** measuring **{area_m2:,.1f} m²**.")
# 
#     # --- PART 2: COMPLETION STATUS ---
#     st.header("Project Progress Status")
#     phases_list = ["Site Work", "Substructure", "Superstructure", "Envelope", "MEP", "Finishes"]
# 
#     cols = st.columns(len(phases_list))
#     actual_data = {}
#     completed_phases_count = 0
# 
#     # Validation Logic for Sequential Selection matching Preview App behavior
#     for i, phase in enumerate(phases_list):
#         with cols[i]:
#             st.subheader(phase)
#             is_done = st.checkbox("Done", key=f"done_{i}")
# 
#             if is_done:
#                 # Check if all previous phases are done
#                 prev_missing = []
#                 for prev_idx in range(i):
#                     if not st.session_state.get(f"done_{prev_idx}", False):
#                         prev_missing.append(phases_list[prev_idx])
# 
#                 if prev_missing:
#                     st.warning(f"⚠️ Non-Sequential! Complete **{prev_missing[0]}** first.")
#                 else:
#                     completed_phases_count += 1
#                     act_c = st.number_input("Act. Cost (€)", key=f"c_{i}", min_value=0.0, value=total_cost * (1/6))
#                     act_t = st.number_input("Act. Days", key=f"t_{i}", min_value=1, step=1, value=int(round(total_time * (1/6))))
#                     actual_data[i] = {"cost": act_c, "time": int(act_t)}
# 
#     # --- PART 3: ANALYSIS ENGINE ---
#     if st.button("📈 RUN PREDICTIVE ANALYSIS", type="primary"):
#         avg_cost_global = assets.get('avg_cost_weights_global', [1/6]*6)
#         avg_time_global = assets.get('avg_time_weights', [1/6]*6)
#         c_weights = assets.get('type_cost_weights', {}).get(building_type, avg_cost_global)
#         t_weights = assets.get('type_time_weights', {}).get(building_type, avg_time_global)
# 
#         proj_vec = [1 if c == f"Type_{building_type}" else 0 for c in assets['encoded_project_cols']]
#         scaled_costs = [total_cost * avg_cost_global[idx] * assets.get('global_overrun_avg', 1.0) for idx in range(6)]
#         core_cont = [area_m2, num_floors, floor_height, total_cost, total_time]
# 
#         if len(assets['param_cols']) == 15: full_input = proj_vec + core_cont + scaled_costs
#         else: full_input = proj_vec + core_cont + [total_cost * c_weights[idx] for idx in range(6)] + [total_time * t_weights[idx] for idx in range(6)] + scaled_costs
# 
#         features = (np.array(full_input).astype(np.float32) - assets['params_min']) / assets['params_range']
#         nn_res = np.array(model(jnp.array([features]))[0]) * assets['output_range'] + assets['output_min']
#         pred_costs, pred_days = nn_res[:6], nn_res[6:]
# 
#         days_planned_cum, pv_points = [0], [0]
#         reality_days, reality_costs, ev_points = [0], [0], [0]
#         pv_acc, cur_ev = 0, 0
# 
#         for i, name in enumerate(phases_list):
#             ec, ed = total_cost * c_weights[i], int(round(total_time * t_weights[i]))
#             pv_acc += ec
#             days_planned_cum.append(days_planned_cum[-1] + ed)
#             pv_points.append(pv_acc)
# 
#             if i in actual_data:
#                 ac, ad = actual_data[i]['cost'], actual_data[i]['time']
#                 cur_ev += ec
#             else:
#                 ac, ad = pred_costs[i], int(round(pred_days[i]))
# 
#             reality_days.append(reality_days[i] + ad)
#             reality_costs.append(reality_costs[i] + ac)
#             if i < completed_phases_count: ev_points.append(cur_ev)
# 
#         fig = go.Figure()
#         fig.add_trace(go.Scatter(x=days_planned_cum, y=pv_points, name='Planned (PV)', line=dict(dash='dot')))
#         fig.add_trace(go.Scatter(x=reality_days[:completed_phases_count+1], y=reality_costs[:completed_phases_count+1], name='Actual (AC)', line=dict(width=3)))
#         fig.add_trace(go.Scatter(x=reality_days[:completed_phases_count+1], y=ev_points, name='Earned (EV)', line=dict(width=3)))
#         fig.add_trace(go.Scatter(x=reality_days[completed_phases_count:], y=reality_costs[completed_phases_count:], name='Forecast', line=dict(dash='dash')))
#         st.plotly_chart(fig, width='stretch')
#

# Install localtunnel globally if not already installed. This helps prevent interactive prompts.
!npm install -g localtunnel

# Run Streamlit in the background and expose it via localtunnel.
# This command should output the public URL directly once connected.
!streamlit run app.py & npx localtunnel --port 8501

!npm install -g localtunnel
!streamlit run app.py & npx localtunnel --port 8501

pip install pyngrok -q    #no need this part?

!pip install pyngrok -q #no need this part?
from pyngrok import ngrok
from google.colab import userdata

# Terminate any previous ngrok tunnels
ngrok.kill()

# Authenticate ngrok using the token from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN') # Make sure you've added your ngrok token to Colab secrets under this name
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Start Streamlit in the background
!streamlit run app.py &

# Create a public URL for Streamlit
public_url = ngrok.connect(8501)
print(f"Streamlit App URL: {public_url}")

"""### Run Streamlit with LocalTunnel (No Ngrok Token Required)

This method uses `localtunnel` to expose your Streamlit app to a public URL. It does not require an `NGROK_AUTH_TOKEN`.

After executing the cell, a public URL will be displayed. Click on the URL to view your Streamlit app. You may need to click past a browser warning as `localtunnel` URLs can sometimes be flagged as untrusted.
"""

# Install localtunnel globally if not already installed.
!npm install -g localtunnel

# Run Streamlit in the background using python -m streamlit and expose it via localtunnel.
# This command should output the public URL directly once connected.
!python -m streamlit run app.py & npx localtunnel --port 8501

"""# Image"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def draw_tech_dashboard():
    # --- 1. SETUP CANVAS ---
    fig, ax = plt.subplots(figsize=(16, 9), dpi=100)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off')

    # Background Colors
    BG_DARK = '#0a0e14'
    PANEL_BLUE = '#141c26'
    ACCENT_TEAL = '#00d4ff'
    ACCENT_GOLD = '#ffcc00'
    ACCENT_RED = '#ff4b4b'
    SUCCESS_GREEN = '#4CAF50'

    fig.patch.set_facecolor(BG_DARK)
    ax.set_facecolor(BG_DARK)

    # --- 2. THE PROCESSOR (CENTER BRAIN) ---
    brain_circle = patches.Circle((50, 65), 12, facecolor='#1a2a3a', edgecolor=ACCENT_TEAL, linewidth=3, zorder=3)
    ax.add_patch(brain_circle)
    ax.text(50, 68, "NEURAL NETWORK\nPROCESSOR", color='white', weight='bold', fontsize=14, ha='center')
    ax.text(50, 60, "(MLP Regressor)", color=ACCENT_TEAL, fontsize=10, ha='center')

    # Abstract connections/nodes inside brain
    for _ in range(12):
        x, y = np.random.uniform(42, 58), np.random.uniform(58, 72)
        ax.scatter(x, y, s=20, color=ACCENT_GOLD, alpha=0.6, zorder=4)

    # --- 3. LEFT PANEL: INPUTS ---
    # Mandatory Inputs
    ax.add_patch(patches.Rectangle((5, 55), 30, 35, facecolor=PANEL_BLUE, edgecolor=ACCENT_TEAL, alpha=0.3, lw=1))
    ax.text(7, 87, "MANDATORY INPUTS", color='white', weight='bold', fontsize=12)

    inputs = ["Building Type", "Total Area (m²)", "Number of floors", "Floor Height", "Est. Cost (€)", "Est. Time (Days)"]
    for i, label in enumerate(inputs):
        y_pos = 81 - (i * 5.5)
        ax.text(8, y_pos, f"▣ {label}", color='white', alpha=0.8, fontsize=10)
        ax.arrow(35, y_pos, 8, 0, head_width=1, head_length=1.5, fc=ACCENT_TEAL, ec=ACCENT_TEAL, alpha=0.4)

    # Monitoring Inputs
    ax.add_patch(patches.Rectangle((5, 15), 30, 30, facecolor=PANEL_BLUE, edgecolor=ACCENT_GOLD, alpha=0.3, lw=1))
    ax.text(7, 41, "LIVE MONITORING", color=ACCENT_GOLD, weight='bold', fontsize=12)
    ax.text(8, 35, "Current Stage Select ▼", color='white', fontsize=10)
    ax.text(8, 28, "Actual Cost (AC)", color='white', fontsize=10)
    ax.text(8, 21, "Actual Time (AD)", color='white', fontsize=10)

    # --- 4. CENTER LOWER: GAUGES ---
    def draw_mini_gauge(x, y, val, label, color):
        ax.add_patch(patches.Wedge((x, y), 6, 0, 180, width=2, facecolor='#222', zorder=1))
        ax.add_patch(patches.Wedge((x, y), 6, 180-(val*180), 180, width=2, facecolor=color, zorder=2))
        ax.text(x, y-3, label, color='white', fontsize=10, ha='center', weight='bold')
        ax.text(x, y+1, f"{val:.2f}", color='white', fontsize=12, ha='center', weight='bold')

    draw_mini_gauge(40, 30, 0.85, "STAGE CPI", ACCENT_GOLD)
    draw_mini_gauge(60, 30, 0.92, "STAGE SPI", ACCENT_TEAL)

    # Correction Factor Arrow
    ax.annotate("CORRECTION FACTOR\n(Updates Future Stages)", xy=(80, 25), xytext=(50, 15),
                arrowprops=dict(arrowstyle="->", color=ACCENT_RED, lw=3, connectionstyle="arc3,rad=-0.2"),
                color=ACCENT_RED, weight='bold', ha='center')

    # --- 5. RIGHT PANEL: OUTPUTS ---
    # Cost Forecast Panel
    ax.add_patch(patches.Rectangle((65, 55), 30, 35, facecolor=PANEL_BLUE, edgecolor=ACCENT_TEAL, alpha=0.5, lw=1))
    ax.text(67, 87, "COST FORECAST", color='white', weight='bold', fontsize=12)

    # Data for the pie chart
    forecast_costs_data = [
        ("Site_Prep", 1.2),
        ("Foundations", 1.8),
        ("Structure", 2.5),
        ("Systems", 1.5),
        ("Finishing", 0.8)
    ]
    labels = [f"{stage}: ${cost:.1f}M" for stage, cost in forecast_costs_data]
    sizes = [cost for stage, cost in forecast_costs_data]
    colors = [ACCENT_GOLD, ACCENT_TEAL, ACCENT_GOLD, ACCENT_TEAL, ACCENT_GOLD] # Using the same accent colors

    # Draw the pie chart
    wedge_sizes = [s / sum(sizes) for s in sizes]
    cumulative_angles = np.cumsum([0] + [s * 360 for s in wedge_sizes])

    for i, size in enumerate(wedge_sizes):
        start_angle = cumulative_angles[i]
        end_angle = cumulative_angles[i+1]
        # Adjust radius and center for placement in the panel
        pie_wedge = patches.Wedge(center=(80, 70), r=10, theta1=start_angle, theta2=end_angle, facecolor=colors[i], edgecolor='white', linewidth=1)
        ax.add_patch(pie_wedge)

        # Add labels to the pie chart
        mid_angle = (start_angle + end_angle) / 2
        x_text = 80 + 12 * np.cos(np.deg2rad(mid_angle))
        y_text = 70 + 12 * np.sin(np.deg2rad(mid_angle))
        ax.text(x_text, y_text, labels[i], color='white', ha='center', va='center', fontsize=8)

    total_forecast = sum(sizes)
    ax.text(67, 50, f"Total Forecast: ${total_forecast:.1f}M", color=SUCCESS_GREEN, weight='bold', fontsize=11)
    ax.text(67, 46, "Completion: 320 Days", color='white', fontsize=10)


    # Final plot adjustments
    plt.tight_layout()
    plt.show()

# Call the function to draw the dashboard
draw_tech_dashboard()

import matplotlib.pyplot as plt
import numpy as np

# Set up the figure
plt.figure(figsize=(14, 8))
plt.style.use('seaborn-v0_8-whitegrid')

# --- 1. DATA DEFINITION ---
# Project is now 5 Stages long
# PV (Planned) ends at Stage 4 (Planned Finish)
# EAC (Actual/Est) ends at Stage 5 (Actual Finish)

# Planned Path (Ends at Stage 4)
planned_time = [0, 1, 2, 3, 4]
planned_val = [0, 100, 200, 300, 300] # Levels off at BAC

# PV (Planned Value) - Now a diagonal straight line from 0 to Stage 5
# To maintain a BAC of 300 at Stage 5:
planned_time = [0, 4.8]
planned_val = [0, 340]

# Actual Path (Solid line up to Stage 1)
time_now = 1
ac_now = 150
ac_x_solid = [0, time_now]
ac_y_solid = [0, ac_now]

# EAC Path (Dashed curve starting at Stage 1, ending at Stage 5)
# Formula adjusted to connect at (1, 150) and hit 350 at Stage 5
ac_x_dashed = np.linspace(time_now, 5, 100)
ac_y_dashed = -12.5 * (ac_x_dashed - 5)**2 + 350

# Earned Value (Up to current progress)
ev_x = [0, time_now]
ev_y = [0, 50]

# --- 2. PLOTTING ---
# Planned Value (PV)
plt.plot(planned_time, planned_val, color='cornflowerblue', label='PV', linewidth=2.5)

# Actual Cost (AC) & Estimate at Completion (EAC)
plt.plot(ac_x_solid, ac_y_solid, color='red', linewidth=3)
plt.plot(ac_x_dashed, ac_y_dashed, color='red', linestyle='--', linewidth=2.5)

# Earned Value (EV)
plt.plot(ev_x, ev_y, color='green', linewidth=3)

# --- 3. STAGE FINISH MARKERS ---
# Planned Finish at Stage 4
plt.axvline(x=4.8, color='blue', linestyle='--', alpha=0.5)
plt.text(4.8, -35, 'PLANNED\nFINISH', ha='center', color='blue', fontweight='bold', fontsize=10)

# Actual/Estimated Finish at Stage 5
plt.axvline(x=5, color='red', linestyle='--', alpha=0.5)
plt.text(5, -35, 'ACTUAL\nFINISH', ha='center', color='red', fontweight='bold', fontsize=10)

# Status Date - NOW A DOTTED BLACK LINE
plt.axvline(x=time_now, color='black', linestyle=':', linewidth=2)
plt.text(time_now, 380, 'Status Date', ha='center', color='black', fontweight='bold',
         bbox=dict(facecolor='white', edgecolor='none', alpha=0.7))

# --- 4. ANNOTATIONS ---
plt.text(1.1, 50, 'EV', color='green', fontsize=12, fontweight='bold')
plt.text(1.1, 115, 'PV', color='cornflowerblue', fontsize=12, fontweight='bold')
plt.text(0.7, 135, 'AC', color='red', fontsize=12, fontweight='bold')
plt.text(4.5, 355, 'EAC', color='red', fontsize=13, fontweight='bold')

# Horizontal budget lines
plt.axhline(y=340, color='cornflowerblue', linestyle=':', alpha=0.4)
plt.axhline(y=350, color='red', linestyle=':', alpha=0.4)

# --- 5. AXIS & STYLING ---
plt.title('EVM Graph: 5-Stage Completion Analysis', fontsize=16, pad=30)
plt.xlabel('Project Stages', loc='right', fontsize=12, labelpad=15)
plt.ylabel('Cost (€)', loc='top', fontsize=12)

# X-axis for 5 stages
plt.xticks(range(6), ['Start', 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4', 'Stage 5'])
plt.yticks([0, 50, 100, 150, 200, 250, 300, 350])

plt.xlim(0, 5.5)
plt.ylim(0, 420)

# Clean aesthetics
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(True, linestyle=':', alpha=0.5)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

def draw_ann_paper_style(
    layer_sizes,
    input_labels=None,
    output_labels=None,
    hidden_labels=None,
    title=None,
    figsize=(10, 12),
    node_size=20,
    line_width=0.35,
    line_grey="0.80"
):

    n_layers = len(layer_sizes)
    max_nodes = max(layer_sizes)

    fig, ax = plt.subplots(figsize=figsize)
    ax.axis("off")

    node_positions = []

    for li, n_nodes in enumerate(layer_sizes):
        slots = [1 - i / (max_nodes - 1) for i in range(max_nodes)] if max_nodes > 1 else [0.5]

        if n_nodes == 1:
            ys = [0.5]
        else:
            start = (max_nodes - n_nodes) // 2
            ys = slots[start:start + n_nodes]

        xs = [li] * n_nodes
        node_positions.append(list(zip(xs, ys)))

    for li in range(n_layers - 1):
        for (x1, y1) in node_positions[li]:
            for (x2, y2) in node_positions[li + 1]:
                ax.plot([x1, x2], [y1, y2], color=line_grey, linewidth=line_width, zorder=1)

    for li in range(n_layers):
        xs = [p[0] for p in node_positions[li]]
        ys = [p[1] for p in node_positions[li]]
        ax.scatter(xs, ys, s=node_size, color="black", zorder=2)

    if input_labels:
        for i, lbl in enumerate(input_labels):
            ax.text(-0.25, node_positions[0][i][1], lbl, ha="right", va="center", fontsize=11)
        ax.text(-0.25, 1.04, f"Input ({layer_sizes[0]})", ha="right", va="bottom", fontsize=11, style="italic")

    if output_labels:
        for i, lbl in enumerate(output_labels):
            ax.text(n_layers - 1 + 0.18, node_positions[-1][i][1], lbl, ha="left", va="center", fontsize=11)
        ax.text(n_layers - 1 + 0.18, 1.04, f"Output ({layer_sizes[-1]})", ha="left", va="bottom", fontsize=11, style="italic")

    if hidden_labels:
        hidden_layer_indices = list(range(1, n_layers - 1))
        for txt, li in zip(hidden_labels, hidden_layer_indices):
            ax.text(li, 1.04, txt, ha="center", va="bottom", fontsize=11, style="italic")

    if title:
        ax.set_title(title, fontsize=13, pad=16)

    ax.set_xlim(-0.6, n_layers - 0.4)
    ax.set_ylim(-0.05, 1.10)

    plt.show()



draw_ann_paper_style(
    layer_sizes=[7, 20, 20, 2],
    input_labels=["Building Type", "Total Area (m²)", "Number of floors", "Floor Height", "Est. Cost (€)", "Est. Time (Days)", "Stage progress"],
    output_labels=["Predicted Cost", "Predicted Time"],
    hidden_labels=["(20)", "(20)"],
    title=None,
    figsize=(10, 13),
    node_size=50,
    line_width=0.50,
    line_grey="0.82"
)